jobs:
- job: VisualStudio2017
  timeoutInMinutes: 90
  pool:
    vmImage: vs2017-win2016
  strategy:
    matrix:
      Debug64:
        BuildPlatform: x64
        BuildConfiguration: Debug
      Release64:
        BuildPlatform: x64
        BuildConfiguration: Release
      Debug32:
        BuildPlatform: Win32
        BuildConfiguration: Debug
      Release32:
        BuildPlatform: Win32
        BuildConfiguration: Release
  steps:
  - script: |
      git clone --depth 1 git://github.com/Microsoft/vcpkg
      call vcpkg\bootstrap-vcpkg
      if %BuildPlatform%==x64 (set VCVARS_ARCH=x64) else set VCVARS_ARCH=x86
      set VCPKG_ARCH=%VCVARS_ARCH%-windows
      echo ##vso[task.setvariable variable=VcVarsArch]%VCVARS_ARCH%
      vcpkg\vcpkg install --triplet %VCPKG_ARCH% openssl xerces-c
      rmdir /s/q vcpkg\packages vcpkg\buildtrees
      echo ##vso[task.setvariable variable=VcPkgInst]%CD%\vcpkg\installed\%VCPKG_ARCH%
    displayName: Vcpkg
  - task: BatchScript@1
    displayName: VcVars
    inputs:
      filename: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvarsall.bat"'
      arguments: $(VcVarsArch)
      modifyEnvironment: true
  - task: BatchScript@1
    displayName: Put perl on PATH
    inputs:
      filename: tools\scripts\prepend_path
      arguments: 'C:\Strawberry\perl\bin'
      modifyEnvironment: true
  - script: |
      if %BuildConfiguration%==Release set OPT=--no-tests --no-debug --optimize
      call configure -v --ace-github-latest --security --xerces3=$(VcPkgInst) --openssl=$(VcPkgInst) %OPT%
      if %BuildConfiguration%==Release (set SLN=DDS_TAOv2.sln) else set SLN=DDS_TAOv2_all.sln
      echo ##vso[task.setvariable variable=BuildSolution]%SLN%
    displayName: Run configure script
  - task: BatchScript@1
    displayName: Setenv from configure script
    inputs:
      filename: setenv.cmd
      modifyEnvironment: true
  - task: VSBuild@1
    displayName: Build solution
    inputs:
      solution: $(BuildSolution)
      platform: $(BuildPlatform)
      configuration: $(BuildConfiguration)
      maximumCpuCount: true

- job: Linux
  timeoutInMinutes: 90
  pool:
    vmImage: ubuntu-16.04
  strategy:
    matrix:
      Debug:
        ConfigOpts: --no-inline
      Release:
        ConfigOpts: --no-debug --optimize
      Safety:
        ConfigOpts: --safety-profile
      SafetyBaseNoBuiltinTopics:
        ConfigOpts: --safety-profile=base --no-built-in-topics
      Security:
        ConfigOpts: --security --features=versioned_namespace=1
        PackageDeps: libxerces-c-dev libssl-dev cmake
      SecurityWithoutFeatures:
        ConfigOpts: --no-inline --no-debug --no-built-in-topics --no-content-subscription --no-ownership-profile --no-object-model-profile --no-persistence-profile --security
        PackageDeps: libxerces-c-dev libssl-dev cmake
      WChar:
        ConfigOpts: --features=uses_wchar=1 --no-inline
      CLANG5:
        ConfigOpts: --compiler=clang++-5.0 --security
        PackageDeps: libxerces-c-dev libssl-dev cmake clang-5.0
        Repo: llvm-toolchain-$(lsb_release -cs)-5.0
      CLANG6:
        ConfigOpts: --compiler=clang++-6.0 --security
        PackageDeps: libxerces-c-dev libssl-dev cmake clang-6.0
        Repo: llvm-toolchain-$(lsb_release -cs)-6.0
      CLANG7:
        ConfigOpts: --compiler=clang++-7 --security
        PackageDeps: libxerces-c-dev libssl-dev cmake clang-7
        Repo: llvm-toolchain-$(lsb_release -cs)-7
      GCC6:
        ConfigOpts: --compiler=g++-6 --no-inline
        PackageDeps: g++-6
      GCC7:
        ConfigOpts: --compiler=g++-7 --no-inline
        PackageDeps: g++-7
  steps:
  - script: |
      wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
      sudo apt-add-repository "deb http://apt.llvm.org/$(lsb_release -cs)/ $(Repo) main"
    displayName: Add repository ($(Repo))
    condition: and(succeeded(), ne(variables['Repo'], ''))
  - script: |
      sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
      sudo apt-get --yes update
      sudo apt-get --yes install libxerces-c-dev libssl-dev $(PackageDeps)
    displayName: install system package dependencies
    condition: and(succeeded(), ne(variables['PackageDeps'], ''))
  - script: ./configure -v --mpcopts="-workers 4" --ace-github-latest $(ConfigOpts)
    displayName: Run configure script
  - script: make -sj6
    displayName: Compile

- job: macOS
  timeoutInMinutes: 90
  pool:
    vmImage: macOS-10.13
  strategy:
    maxParallel: 2
    matrix:
      Debug:
        ConfigOpts: --no-inline
      Release:
        ConfigOpts: --no-debug --optimize
  steps:
  - script: ./configure -v --ace-github-latest $(ConfigOpts)
    displayName: Run configure script
  - script: make -sj6
    displayName: Compile
