/*
 *
 *
 * Distributed under the OpenDDS License.
 * See: http://www.opendds.org/license.html
 */

#pragma DCPS_DATA_TYPE "Complex_Idl::Data"
#pragma DCPS_DATA_KEY "Complex_Idl::Data id"

#include "Common.idl"

#include "tao/OctetSeq.pidl"

module Complex_Idl {

    enum DataType { DATA_IDL, DATA_STREAM };

    union DataUnion switch (DataType) {
        case DATA_IDL:      Quote idl_quote;
        case DATA_STREAM:   CORBA::OctetSeq stream;
    };

    struct Data {
        long id;
        DataUnion payload;
    };
};
