


## DCPS_DEFAULT_DISCOVERY ASPECT
if (NO_OPENDDS_SAFETY_PROFILE)
  set(DCPS_DEFAULT_DISCOVERY_LINK_LIBRARIES OpenDDS_InfoRepoDiscovery)
else()
  set(DCPS_DEFAULT_DISCOVERY_LINK_LIBRARIES OpenDDS_Rtps)
endif()

## DCPS_TRANSPORTS_FOR_TEST ASPECT
if (NO_OPENDDS_SAFETY_PROFILE)
  set(DCPS_TRANSPORTS_FOR_TEST_LINK_LIBRARIES
    OpenDDS_Tcp OpenDDS_Udp OpenDDS_Multicast OpenDDS_Rtps_Udp OpenDDS_Shmem
  )
  # if(${CMAKE_SYSTEM_NAME} MATCHES "Darwin")
  #   set(TEST_EXCLUDE_LABELS SHMEM CACHE INTERNAL "")
  # else()
  #   list(APPEND DCPS_TRANSPORTS_FOR_TEST_LINK_LIBRARIES OpenDDS_Shmem)
  # endif()
else()
  set(DCPS_TRANSPORTS_FOR_TEST_LINK_LIBRARIES OpenDDS_Rtps_Udp)
endif()


## FACE ASPECT
set(FACE_LINK_LIBRARIES OpenDDS_FACE)
set(FACE_TAO_IDL_FLAGS -SS -Wb,no_fixed_err)
set(FACE_DDS_IDL_FLAGS -GfaceTS -Lface)


